version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: jeopardy-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jeopardy
    ports:
      - "5432:5432"
    volumes:
      - jeopardy_postgres_data:/var/lib/postgresql/data

volumes:
  jeopardy_postgres_data:
